// <auto-generated />
using System;
using LicenseManagementService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicenseManagementService.Migrations
{
    [DbContext(typeof(LicenseContext))]
    partial class LicenseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LicenseManagementService.Models.License", b =>
                {
                    b.Property<string>("product_license")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("companyId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("expired_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("issuedate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("productId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("product_license");

                    b.HasIndex("productId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("LicenseManagementService.Models.Product", b =>
                {
                    b.Property<int?>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<string>("productName")
                        .HasColumnType("longtext");

                    b.HasKey("productId");

                    b.ToTable("products_by");
                });

            modelBuilder.Entity("LicenseManagementService.Models.License", b =>
                {
                    b.HasOne("LicenseManagementService.Models.Product", "products_by")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("products_by");
                });
#pragma warning restore 612, 618
        }
    }
}
