// <auto-generated />
using System;
using LicenseManagementService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicenseManagementService.Migrations
{
    [DbContext(typeof(LicenseContext))]
    partial class LicenseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LicenseManagementService.Models.License", b =>
                {
                    b.Property<string>("product_license")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("expired_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("product_name")
                        .HasColumnType("longtext");

                    b.Property<string>("product_status")
                        .HasColumnType("longtext");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("product_license");

                    b.ToTable("products");
                });
#pragma warning restore 612, 618
        }
    }
}
